### PR TITLE
Changed Error code and Updated Dependancies

### PR DESCRIPTION
**Pull request by ftechiesnitin**
- Google Cloud Pub/Sub TOPIC EXISTS Error Code Changed from 409 to 6.

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]
LGTM

**Comment by idoshamun** [comment]
Thanks for the contribution!

**Comment by ftechiesnitin** [comment]
@idoshamun Is there any issue with the build. I see the build is failing.

**Comment by idoshamun** [comment]
Yes something with the certificates, it doesn't have to do with this PR.
I already released your fix :)

**Comment by ftechiesnitin** [comment]
Thanks.

**Pull request merged**
